(()=>{
const c=document.querySelector('#game'),x=c.getContext('2d'),W=c.width,H=c.height,keys={};
const atlas=new Image();atlas.src='assets/jungle-sprite-atlas-v1.png';
const apeAtlas=new Image();apeAtlas.src='assets/ape-animation-atlas-v2.png';
const ui={score:document.querySelector('#score'),hp:document.querySelector('#health'),best:document.querySelector('#best'),debug:document.querySelector('#debug'),over:document.querySelector('#start'),play:document.querySelector('#play'),toast:document.querySelector('#toast')};
const globe={cx:640,cy:610,r:520,rot:0,tilt:0,vx:0,vy:0};
let ape,things,terrain,drops,score=0,hp=3,best=+(localStorage.apeGlobeBest||0),run=false,last=0,t=0,spawn=1,shake=0,drag=false,dragX=0,dragY=0;
const kinds=['tree','tree','tree','rock','tree','log','tree','rock','tree'];
function reset(){score=0;hp=3;t=0;spawn=.8;globe.rot=globe.tilt=globe.vx=globe.vy=0;ape={lon:0,lat:0,x:globe.cx,y:globe.cy-58,groundY:globe.cy,runSpeed:0,centerDist:0,state:'run',timer:0,face:1,navSign:1};drops=[];things=[];terrain=[];let rings=[-1.16,-.72,-.26,.26,.72,1.16],pattern=['tree','rock','log','tree','rock','tree'];for(let r=0;r<rings.length;r++)for(let j=0;j<7;j++){let type=pattern[(r*2+j)%pattern.length],lon=-Math.PI+j*(Math.PI*2/7)+(r%2)*Math.PI/7,lat=rings[r]+((j%2)*2-1)*.035,size=type==='tree'?1.18+(j%3)*.14:type==='log'?.82:.72;things.push({lon,lat,type,size});}for(let i=0;i<420;i++){let u=(i+.5)/420,lat=Math.asin(2*u-1),lon=(i*2.399963229728653)% (Math.PI*2)-Math.PI;terrain.push({lon,lat,size:1+(i%6),tone:i%4});}hud();ui.debug.textContent='CENTER GAP 0°';}
function hud(){best=Math.max(best,score);localStorage.apeGlobeBest=best;ui.score.textContent=`🍌  ${score}`;ui.hp.textContent='♥ '.repeat(hp).trim()||'—';ui.best.textContent=`🏆  ${best*50}`;}
function say(s,col='#fff'){ui.toast.textContent=s;ui.toast.style.color=col;ui.toast.classList.add('show');clearTimeout(say.q);say.q=setTimeout(()=>ui.toast.classList.remove('show'),700);}
function knock(s){if(ape.state!=='run')return;ape.state='trip';ape.timer=1.9;ape.runSpeed=0;hp--;shake=16;say(s,'#ff9b88');hud();}
function pos(o){let cl=Math.cos(o.lat),wx=cl*Math.sin(o.lon),wy=Math.sin(o.lat),wz=cl*Math.cos(o.lon),cr=Math.cos(globe.rot),sr=Math.sin(globe.rot),ct=Math.cos(globe.tilt),st=Math.sin(globe.tilt),rx=wx*cr+wz*sr,rz=-wx*sr+wz*cr,ry=wy*ct-rz*st,depth=wy*st+rz*ct,front=Math.max(0,depth),radius=1+(o.alt||0),X=globe.cx+rx*globe.r*radius,Y=globe.cy-ry*globe.r*radius,radial=Math.hypot(rx,ry),normalRot=radial>.08?Math.atan2(rx,-ry):0,vertical=.46+radial*.54;return{x:X,y:Y,depth,s:(o.size||1)*(.3+front*.9),rot:normalRot,vertical,nx:rx,ny:-ry,baseError:Math.abs(Math.hypot(X-globe.cx,Y-globe.cy)-globe.r*radius*Math.sqrt(Math.max(0,1-depth*depth)))};}
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
function update(dt){if(!run)return;t+=dt;shake=Math.max(0,shake-dt*22);let turn=(keys.ArrowRight||keys.KeyD?1:0)-(keys.ArrowLeft||keys.KeyA?1:0),pitch=(keys.ArrowDown||keys.KeyS?1:0)-(keys.ArrowUp||keys.KeyW?1:0);globe.vx+=turn*dt*3;globe.vy+=pitch*dt*2.4;globe.vx=Math.max(-1.3,Math.min(1.3,globe.vx));globe.vy=Math.max(-1.05,Math.min(1.05,globe.vy));globe.rot=wrap(globe.rot+globe.vx*dt);globe.tilt=wrap(globe.tilt+globe.vy*dt);globe.vx*=Math.pow(.075,dt);globe.vy*=Math.pow(.075,dt);
 let ctg=Math.cos(globe.tilt),tx=-ctg*Math.sin(globe.rot),ty=Math.sin(globe.tilt),tz=ctg*Math.cos(globe.rot),targetLon=Math.atan2(tx,tz),targetLat=Math.asin(Math.max(-1,Math.min(1,ty))),dLon=wrap(targetLon-ape.lon),dLat=targetLat-ape.lat,dist=Math.hypot(dLon*Math.cos((ape.lat+targetLat)/2),dLat),ap0=pos({lon:ape.lon,lat:ape.lat,size:1}),desired=Math.sign(640-ap0.x)||ape.face;ape.centerDist=dist;ui.debug.textContent=`CENTER GAP ${(dist*180/Math.PI).toFixed(1)}°`;
 if(ape.dragExpected){console.assert(dist>.035,'Strong globe drag must displace ape from center');ape.dragExpected=false;}
 if(ape.state==='run'){
  ape.recognize=Math.max(0,(ape.recognize||0)-dt);
  if(desired!==ape.face&&dist>.07){if(ape.runSpeed>.16&&Math.abs(globe.vx)>.2){ape.state='trip';ape.timer=1.4;ape.pendingFace=desired;ape.runSpeed=0;say('DIRECTION STUMBLE!','#ffb078');}else{ape.state='turn';ape.timer=.32;ape.pendingFace=desired;ape.runSpeed=0;}}
  else if(ape.recognize<=0&&dist>.018){let urgency=Math.min(1,dist/.65),targetSpeed=.11+urgency*.22;ape.runSpeed+=(targetSpeed-ape.runSpeed)*Math.min(1,dt*2.2);let cm=Math.max(.18,Math.cos(ape.lat)),ux=dLon*cm/dist,uy=dLat/dist,avoidX=0,avoidY=0,nearest=null;for(const o of things){let ox=wrap(o.lon-ape.lon)*cm,oy=o.lat-ape.lat,od=Math.hypot(ox,oy),ahead=ox*ux+oy*uy;if(od<.29&&ahead>0){let side=ux*oy-uy*ox;if(Math.abs(side)>.015)ape.navSign=side>0?-1:1;let force=(.29-od)/.29;avoidX+=-uy*ape.navSign*force*1.8;avoidY+=ux*ape.navSign*force*1.8;if(!nearest||od<nearest.od)nearest={o,od};}}let mx=ux+avoidX,my=uy+avoidY,ml=Math.hypot(mx,my)||1;mx/=ml;my/=ml;let step=Math.min(dist,ape.runSpeed*dt),nl=wrap(ape.lon+mx/cm*step),nt=Math.max(-1.48,Math.min(1.48,ape.lat+my*step)),hit=null;for(const o of things){let od=Math.hypot(wrap(o.lon-nl)*Math.max(.18,Math.cos(nt)),o.lat-nt),clear=o.type==='tree'?.085:.065;if(od<clear){hit=o;break;}}if(hit){ape.navSign*=-1;let sx=-uy*ape.navSign,sy=ux*ape.navSign,nl2=wrap(ape.lon+sx/cm*step),nt2=Math.max(-1.48,Math.min(1.48,ape.lat+sy*step)),safe=things.every(o=>Math.hypot(wrap(o.lon-nl2)*Math.max(.18,Math.cos(nt2)),o.lat-nt2)> (o.type==='tree'?.085:.065));if(safe){ape.lon=nl2;ape.lat=nt2;say('CHOOSING A PATH','#bdf58f');}else if(hit.type==='tree')say('ROUTING AROUND TREE','#ffe398');else knock(hit.type==='rock'?'ROCK TRIP!':'LOG TRIP!');}else{ape.lon=nl;ape.lat=nt;}}
  else ape.runSpeed*=Math.pow(.12,dt);
 }else{ape.timer-=dt;ape.runSpeed=0;if(ape.state==='turn'&&ape.timer<=0){ape.face=ape.pendingFace;ape.state='run';ape.recognize=.12;}else{if(ape.state==='trip'&&ape.timer<.9)ape.state='down';if(ape.state==='down'&&ape.timer<.35)ape.state='stand';if(ape.timer<=0&&ape.state!=='turn'){if(hp<=0){run=false;ui.over.querySelector('h2').textContent='Knocked out on the little world.';ui.over.querySelector('p').textContent=`You caught ${score} bananas.`;ui.play.textContent='RUN AGAIN';ui.over.classList.remove('hidden');}else{ape.face=ape.pendingFace||ape.face;ape.state='run';ape.recognize=.14;}}}}
 let ap=pos({lon:ape.lon,lat:ape.lat,size:1});ape.x=ap.x;ape.groundY=ap.y;ape.y=ap.y-58;ape.depth=ap.depth;
 spawn-=dt;if(spawn<=0){spawn=1.05+Math.random()*1.35;let ctg=Math.cos(globe.tilt),tx=-ctg*Math.sin(globe.rot),ty=Math.sin(globe.tilt),tz=ctg*Math.cos(globe.rot),baseLon=Math.atan2(tx,tz),baseLat=Math.asin(Math.max(-1,Math.min(1,ty)));drops.push({type:Math.random()<.82?'banana':'rock',lon:wrap(baseLon+(Math.random()-.5)*1.05),lat:Math.max(-1.35,Math.min(1.35,baseLat+(Math.random()-.5)*.85)),alt:.72,fallSpeed:.18+Math.random()*.08,rot:0});}for(const d of drops){d.alt=Math.max(0,d.alt-d.fallSpeed*dt);d.rot+=dt*4;let bp=pos(d);d.x=bp.x;d.y=bp.y;if(!d.dead&&d.alt<.07&&Math.hypot(wrap(d.lon-ape.lon)*Math.max(.18,Math.cos(ape.lat)),d.lat-ape.lat)<.1){d.dead=true;if(d.type==='banana'){score++;say('+1 BANANA','#ffe26b');hud();}else knock('FALLING ROCK!');}if(d.alt<=0)d.dead=true;}drops=drops.filter(d=>!d.dead);
}
function ell(X,Y,rx,ry,col){x.fillStyle=col;x.beginPath();x.ellipse(X,Y,rx,ry,0,0,Math.PI*2);x.fill();}
function tile(col,row,dx,dy,dw,dh){if(!atlas.complete||!atlas.naturalWidth)return false;x.drawImage(atlas,col*384,row*512,384,512,dx,dy,dw,dh);return true;}
function apeTile(col,row,dx,dy,dw,dh){if(!apeAtlas.complete||!apeAtlas.naturalWidth)return false;x.drawImage(apeAtlas,col*384,row*512,384,512,dx,dy,dw,dh);return true;}
function spriteThing(o,p){if(p.depth<.42)return;x.save();let near=Math.max(0,Math.min(1,(p.depth-.42)/.58)),alpha=.38+near*.62;x.globalAlpha=alpha;x.filter=near<.38?`blur(${(1-near/.38)*1.7}px)`:'none';x.translate(p.x,p.y);x.rotate(p.rot);x.scale(p.s,p.s*p.vertical);x.shadowColor='#061b12aa';x.shadowBlur=7+near*10;x.shadowOffsetY=4+near*5;if(o.type==='tree'){let side=3+5*(1-p.depth);x.globalAlpha=alpha*.18;tile(1,0,-73-side,-201,146,210);x.globalAlpha=alpha*.32;tile(1,0,-73+side,-201,146,210);x.globalAlpha=alpha;tile(1,0,-73,-201,146,210);ell(0,5,28,9,'#214c27aa');}else if(o.type==='log'){if(!tile(2,0,-67,-78,134,88))thing(o,p);}else{if(!tile(3,0,-53,-82,106,90))thing(o,p);}x.restore();}
function fallProgress(d){return Math.max(0,Math.min(1,1-d.alt/.72));}
function dropShadow(d){let p=fallProgress(d),bp=pos({lon:d.lon,lat:d.lat,size:1});x.save();x.globalAlpha=(.04+p*.42)*Math.max(.25,bp.depth);x.translate(bp.x,bp.y);x.rotate(bp.rot);ell(0,3,6+p*29,2+p*9,'#071b16');x.restore();}
function spriteDrop(d){let p=fallProgress(d),bp=pos({lon:d.lon,lat:d.lat,size:1}),ip=pos({lon:d.lon,lat:d.lat,alt:d.alt,size:1}),depth=Math.max(.15,bp.depth),sc=(.28+p*.72)*(.55+depth*.45);x.save();x.globalAlpha=(.22+p*.78)*(.45+depth*.55);x.filter=p<.4?`blur(${(1-p/.4)*2.8}px)`:'none';x.translate(ip.x,ip.y);x.scale(sc,sc);x.rotate(d.rot*.18);if(d.type==='banana'){x.shadowColor='#ffe351';x.shadowBlur=8+p*25;if(!tile(0,1,-42,-48,84,96))drop(d);}else{x.shadowColor='#ff3b28';x.shadowBlur=6+p*20;if(!tile(1,1,-40,-45,80,90))drop(d);}x.restore();}
function spriteMonkey(){x.save();x.translate(ape.x,ape.y);let speed=ape.runSpeed*650,moving=ape.state==='run'&&speed>16,col=3,row=1;if(moving){row=0;col=(Math.floor(t*(5+Math.min(7,speed/38)))%2)*2;}else if(ape.state==='trip'){row=1;col=0;}else if(ape.state==='down'){row=1;col=1;}else if(ape.state==='stand'){row=1;col=ape.timer>.22?2:3;}let runY=[-89,-108,-106,-97],recoveryY=[-53,-77,-96,-86],frameY=row===0?runY[col]:recoveryY[col];x.scale(ape.face,1);x.shadowColor='#071b12aa';x.shadowBlur=12;if(!apeTile(col,row,-76,frameY,152,172))tile(0,0,-59,-82,118,145);x.restore();}
function bg(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#315d89');g.addColorStop(.46,'#71aac3');g.addColorStop(.78,'#c6dcb6');g.addColorStop(1,'#e0c179');x.fillStyle=g;x.fillRect(0,0,W,H);for(let i=0;i<7;i++){let bx=80+i*205;x.strokeStyle=i%2?'#ffd66d22':'#9ee8ff22';x.lineWidth=14;x.beginPath();x.moveTo(bx,0);x.lineTo(bx-80,H);x.stroke();}x.globalAlpha=.3;for(let i=0;i<10;i++)ell((i*181+t*5)%1400-70,72+(i%4)*50,70,15,'#fff');x.globalAlpha=1;let haze=x.createLinearGradient(0,300,0,560);haze.addColorStop(0,'#b8d9d000');haze.addColorStop(1,'#e9ddaa99');x.fillStyle=haze;x.fillRect(0,300,W,300);}
function ball(){x.save();x.shadowColor='#0b3e24aa';x.shadowBlur=45;x.beginPath();x.arc(globe.cx,globe.cy,globe.r,0,Math.PI*2);x.clip();let g=x.createRadialGradient(globe.cx-150,globe.cy-190,40,globe.cx,globe.cy,globe.r);g.addColorStop(0,'#a8df62');g.addColorStop(.52,'#58a843');g.addColorStop(.84,'#246b42');g.addColorStop(1,'#12382f');x.fillStyle=g;x.fillRect(globe.cx-globe.r,globe.cy-globe.r,globe.r*2,globe.r*2);x.shadowBlur=0;for(const q of terrain){let p=pos(q);if(p.depth<.04)continue;let col=['#d9df62aa','#194f32aa','#87bd4faa','#d5aa4c88'][q.tone];ell(p.x,p.y,q.size*p.s,q.size*p.s*.62,col);}x.globalAlpha=1;x.restore();x.shadowBlur=0;x.strokeStyle='#d9f59a';x.lineWidth=7;x.beginPath();x.arc(globe.cx,globe.cy,globe.r,0,Math.PI*2);x.stroke();}
function thing(o,p){if(p.depth<.45)return;x.save();x.translate(p.x,p.y);x.scale(p.s,p.s);if(o.type==='tree'){x.fillStyle='#6c4025';x.fillRect(-11,-116,22,118);ell(0,-142,46,62,'#226c43');ell(-32,-130,30,42,'#34965a');ell(34,-128,31,45,'#44aa67');}else if(o.type==='rock'){x.fillStyle='#657578';x.beginPath();x.moveTo(-35,0);x.lineTo(-26,-32);x.lineTo(2,-49);x.lineTo(36,-25);x.lineTo(40,0);x.fill();x.fillStyle='#9ba8a5';x.beginPath();x.moveTo(-20,-29);x.lineTo(2,-44);x.lineTo(14,-22);x.fill();}else{x.strokeStyle='#724426';x.lineWidth=28;x.lineCap='round';x.beginPath();x.moveTo(-45,-13);x.lineTo(45,-13);x.stroke();x.strokeStyle='#a36b3c';x.lineWidth=4;for(let q=-35;q<42;q+=18){x.beginPath();x.moveTo(q,-26);x.lineTo(q+8,0);x.stroke();}}x.restore();}
function drop(d){x.save();x.translate(d.x,d.y);x.rotate(d.rot);if(d.type==='banana'){x.shadowColor='#ffe34e';x.shadowBlur=28;x.strokeStyle='#fff07b';x.lineWidth=16;x.lineCap='round';x.beginPath();x.arc(0,0,25,.2,2.55);x.stroke();x.shadowBlur=0;x.strokeStyle='#e9a918';x.lineWidth=4;x.stroke();}else{x.shadowColor='#ff3e2f';x.shadowBlur=18;let rg=x.createRadialGradient(-7,-8,2,0,0,29);rg.addColorStop(0,'#66726a');rg.addColorStop(1,'#17211e');x.fillStyle=rg;x.beginPath();for(let i=0;i<16;i++){let a=i*Math.PI/8,r=i%2?25:31;x.lineTo(Math.cos(a)*r,Math.sin(a)*r);}x.fill();x.strokeStyle='#ff704f';x.lineWidth=4;x.beginPath();x.moveTo(9,-23);x.quadraticCurveTo(20,-38,28,-29);x.stroke();x.fillStyle='#f4ede0';x.beginPath();x.arc(0,2,13,0,Math.PI*2);x.fill();ell(-5,-1,3,5,'#17211e');ell(5,-1,3,5,'#17211e');}x.restore();}
function monkey(){x.save();x.translate(ape.x,ape.y);x.scale(ape.face,1);let r=0;if(ape.state==='trip')r=Math.min(1.38,(1.9-ape.timer)*3);if(ape.state==='down')r=1.52;if(ape.state==='stand')r=Math.max(0,ape.timer*3.2);x.rotate(r);let moving=ape.state==='run'&&(Math.abs(ape.vx)>15||Math.abs(globe.vx)+Math.abs(globe.vy)>.012),sw=moving?Math.sin(t*15)*15:0,b=moving?Math.sin(t*15)*3:0;x.translate(0,b);ell(0,0,34,45,'#49362e');ell(0,-44,37,34,'#4d382f');ell(0,-38,25,22,'#bd8d65');ell(-33,-43,11,16,'#3c2c26');ell(33,-43,11,16,'#3c2c26');ell(-10,-49,4,5,'#111');ell(10,-49,4,5,'#111');x.strokeStyle='#2b1f1a';x.lineWidth=4;x.beginPath();x.arc(0,-36,9,.2,2.9);x.stroke();x.strokeStyle='#49362e';x.lineWidth=13;x.lineCap='round';x.beginPath();x.moveTo(-25,-4);x.lineTo(-39+sw,30);x.moveTo(25,-4);x.lineTo(39-sw,30);x.moveTo(-15,34);x.lineTo(-20-sw*.4,64);x.moveTo(15,34);x.lineTo(20+sw*.4,64);x.stroke();x.restore();}
function render(){x.save();if(shake)x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);bg();x.translate(640,520);x.scale(1.13,1.13);x.translate(-640,-520);ball();for(const d of drops)dropShadow(d);let visible=things.map(o=>({o,p:pos(o)})).sort((a,b)=>a.p.y-b.p.y),contactY=ape.groundY;for(const v of visible.filter(v=>v.p.y<=contactY))spriteThing(v.o,v.p);for(const d of drops)spriteDrop(d);if(ape.depth>0){ell(ape.x,contactY+3,38,9,'#081b1288');spriteMonkey();}for(const v of visible.filter(v=>v.p.y>contactY))spriteThing(v.o,v.p);x.restore();let pg=x.createLinearGradient(420,0,860,0);pg.addColorStop(0,'#102115aa');pg.addColorStop(.5,'#28321bd8');pg.addColorStop(1,'#102115aa');x.fillStyle=pg;x.strokeStyle='#d8d99a88';x.lineWidth=2;x.beginPath();x.roundRect(420,H-70,440,50,22);x.fill();x.stroke();x.textAlign='center';x.fillStyle='#aef36f';x.font='900 17px system-ui';x.fillText('🍌  CATCH',520,H-39);x.fillStyle='#ffffff77';x.fillText('|',640,H-39);x.fillStyle='#ff7058';x.fillText('☠  AVOID',755,H-39);x.fillStyle='#fff2c2';x.font='800 13px system-ui';x.fillText('↔  SWIPE / DRAG TO ROTATE  ↕',640,H-86);x.textAlign='left';}
setInterval(()=>{if(!run)return;for(const o of things){let p=pos(o);console.assert(p.baseError<1,'Prop base diverged from shared sphere projection',o.type,p.baseError);}let ap=pos({lon:ape.lon,lat:ape.lat,size:1});console.assert(ap.baseError<1,'Ape contact diverged from shared sphere projection',ap.baseError);},1000);
function frame(n){let dt=Math.min(.033,(n-last)/1000||0);last=n;update(dt);render();requestAnimationFrame(frame);}addEventListener('keydown',e=>{keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='KeyR'){reset();run=true;ui.over.classList.add('hidden');}});addEventListener('keyup',e=>keys[e.code]=false);c.addEventListener('pointerdown',e=>{drag=true;dragX=e.clientX;dragY=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(drag){let dx=e.clientX-dragX,dy=e.clientY-dragY;globe.rot=wrap(globe.rot+dx*.0028);globe.tilt=wrap(globe.tilt+dy*.00235);globe.vx=Math.max(-1.3,Math.min(1.3,dx*.025));globe.vy=Math.max(-1.05,Math.min(1.05,dy*.021));ape.recognize=.34;if(Math.hypot(dx,dy)>25)ape.dragExpected=true;dragX=e.clientX;dragY=e.clientY}});c.addEventListener('pointerup',()=>drag=false);c.addEventListener('pointercancel',()=>drag=false);ui.play.onclick=()=>{reset();run=true;ui.over.classList.add('hidden');};reset();requestAnimationFrame(frame);
})();
