(()=>{const c=document.querySelector('#game'),x=c.getContext('2d'),scoreEl=document.querySelector('#score'),hpEl=document.querySelector('#hp'),livesEl=document.querySelector('#lives'),intro=document.querySelector('#intro'),apeSprite=new Image();apeSprite.src='assets/hero/banana-runner-cycle-2d-v1.png';let W=390,H=844,running=false,last=0,scroll=0,score=0,hp=5,lives=3,pointer=false,startX=0,startY=0,lastX=0,targetV=0,spawn=0;const ape={x:195,y:655,vy:0,vx:0,onGround:true,face:1,step:0,hit:0},items=[];
function resize(){const d=Math.min(devicePixelRatio||1,1.5),r=c.getBoundingClientRect();c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);x.setTransform(c.width/390,0,0,c.height/844,0,0)}addEventListener('resize',resize);resize();
function rounded(px,py,w,h,r){x.beginPath();x.roundRect(px,py,w,h,r);x.fill()}
function drawMonkey(){x.save();x.translate(ape.x,ape.y);x.scale(ape.face,1);const moving=Math.abs(ape.vx)>12,bob=moving?Math.sin(ape.step*2)*3:0,frame=moving?Math.floor(ape.step)%4:1;if(apeSprite.complete&&apeSprite.naturalWidth){const sw=apeSprite.naturalWidth/4,sh=apeSprite.naturalHeight;x.rotate(moving?Math.max(-.09,Math.min(.09,ape.vx/2200)):0);x.drawImage(apeSprite,frame*sw,0,sw,sh,-72,-151+bob,144,144)}else{x.font='70px serif';x.textAlign='center';x.fillText('🐵',0,-40)}x.restore()}
function addItem(){const good=Math.random()<.68,type=good?(Math.random()<.6?'banana':Math.random()<.8?'coin':'heart'):(Math.random()<.55?'rock':'bomb');items.push({x:38+Math.random()*314,y:100,vy:type==='rock'?245:165+Math.random()*35,type,good,spin:0,landed:0})}
function collect(it){if(it.type==='banana'){score+=2;hp=Math.min(5,hp+1)}else if(it.type==='coin')score+=4;else if(it.type==='heart'){if(lives<3)lives++}else{hp-=it.type==='bomb'?2:1;ape.hit=.45;if(hp<=0){lives--;hp=5;if(lives<=0){running=false;intro.hidden=false;intro.querySelector('h1').textContent='TRY AGAIN';intro.querySelector('p').textContent=`You scored ${score} points.`}}}scoreEl.textContent=`⭐ ${score}/30`;hpEl.textContent=`HP ${'●'.repeat(hp)}${'○'.repeat(5-hp)}`;livesEl.textContent=`♥ ×${lives}`;if(score>=30){running=false;intro.hidden=false;intro.querySelector('h1').textContent='WORLD CLEAR!';intro.querySelector('p').textContent='Jungle complete. More worlds can follow this same format.'}}
function update(dt){ape.vx+=(targetV-ape.vx)*Math.min(1,dt*18);targetV*=Math.max(0,1-dt*8);ape.x+=(195-ape.x)*Math.min(1,dt*14);if(Math.abs(ape.vx)>8)ape.face=Math.sign(ape.vx);ape.step+=dt*(5+Math.abs(ape.vx)*.05);ape.vy+=980*dt;ape.y+=ape.vy*dt;if(ape.y>=655){ape.y=655;ape.vy=0;ape.onGround=true}ape.hit=Math.max(0,ape.hit-dt);spawn-=dt;if(spawn<=0){addItem();spawn=.8+Math.random()*1.05}for(let i=items.length-1;i>=0;i--){const q=items[i];if(!q.landed){q.y+=q.vy*dt;q.vy+=46*dt;q.spin+=dt*(q.good?3:6);if(q.y>=625){q.y=625;q.landed=6;q.vy=0}}else q.landed-=dt;if(Math.hypot(q.x-ape.x,q.y-(ape.y-24))<45){collect(q);items.splice(i,1)}else if(q.landed<=0&&q.y>=625)items.splice(i,1)}}
function draw(){const g=x.createLinearGradient(0,0,0,620);g.addColorStop(0,'#3f9de1');g.addColorStop(1,'#b9edeb');x.fillStyle=g;x.fillRect(0,0,390,844);x.fillStyle='#fff9';for(let i=0;i<5;i++){x.beginPath();x.ellipse(((i*130-scroll*.08)%620)-100,125+(i%2)*80,70,22,0,0,7);x.fill()}x.fillStyle='#986230';x.fillRect(((scroll*.16)%500)-100,92,88,26);x.fillStyle='#f3c144';x.fillRect(((scroll*.16)%500)-72,75,54,15);x.fillStyle='#2e8740';x.beginPath();x.moveTo(0,520);for(let i=0;i<=13;i++)x.lineTo(i*32,520+Math.sin(i*1.7+scroll*.01)*18);x.lineTo(390,844);x.lineTo(0,844);x.fill();x.fillStyle='#4fae42';x.fillRect(0,610,390,234);x.fillStyle='#7abf3b';for(let i=0;i<20;i++){const px=((i*67-scroll*.45)%500)-60;x.beginPath();x.ellipse(px,635+(i%4)*34,35,15,0,0,7);x.fill()}for(const q of items){if(!q.landed){x.fillStyle=q.good?'#fff08a88':'#ff665599';x.beginPath();x.ellipse(q.x,627,24,7,0,0,7);x.fill();x.strokeStyle=q.good?'#fff7a4':'#ff735f';x.lineWidth=3;x.setLineDash([7,7]);x.beginPath();x.moveTo(q.x,q.y+18);x.lineTo(q.x,610);x.stroke();x.setLineDash([])}x.save();x.translate(q.x,q.y);x.rotate(q.spin);x.font='42px serif';x.textAlign='center';x.fillText(q.type==='banana'?'🍌':q.type==='coin'?'🪙':q.type==='heart'?'❤️':q.type==='rock'?'🪨':'💣',0,0);x.restore()}if(ape.hit&&Math.floor(ape.hit*14)%2===0)x.globalAlpha=.35;drawMonkey();x.globalAlpha=1}
function frame(t){const dt=Math.min(.035,(t-last)/1000||0);last=t;if(running)update(dt);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function down(e){pointer=true;startX=lastX=e.clientX;startY=e.clientY;targetV=0;c.setPointerCapture?.(e.pointerId)}function move(e){if(!pointer)return;const dx=e.clientX-lastX,dy=e.clientY-startY;lastX=e.clientX;scroll-=dx*1.35;for(const q of items)q.x+=dx*1.35;targetV=Math.max(-280,Math.min(280,-dx*48));if(dy<-38&&ape.onGround){ape.vy=-470;ape.onGround=false;startY=e.clientY}}function up(){pointer=false;targetV=0}c.addEventListener('pointerdown',down);c.addEventListener('pointermove',move);c.addEventListener('pointerup',up);c.addEventListener('pointercancel',up);document.querySelector('#start').onclick=()=>{score=0;hp=5;lives=3;items.length=0;scoreEl.textContent='⭐ 0/30';hpEl.textContent='HP ●●●●●';livesEl.textContent='♥ ×3';intro.hidden=true;running=true;last=performance.now()};document.documentElement.dataset.sideScroller='ready';})();
